forum/urls.py
from django.urls import path, include
from . import views
app_name='forum'

urlpatterns = [
    path('', views.forum,name="forum"),
]

home/urls.py
from django.urls import path, include
from . import views
app_name='home'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('explore', views.explore, name = 'explore'),
    path('tryout', views.tryout, name = 'tryout'),
    path('recipe/<id>', views.recipe, name='recipe'),
    path('register', views.register, name='register'),
    path('registered', views.registered, name='registered'),
    path('login',views.login, name='login'),
    path('base', views.base, name='base'),
    path('findchefs', views.findchefs, name='find'),
    path('contact', views.contact, name='contact'),
    path('cont', views.cont, name='cont'),
    path('diet', views.diet, name='diet'),
    path('select/<id_1>', views.select, name='select'),
    path('insert', views.insert, name='insert'),
]

recipe_website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('forum/', include('forum.urls')),
    path('uploadform/', include('uploadform.urls')),
]

uploadform/urls.py
from django.urls import path
from . import views
app_name='uploadform'


urlpatterns = [
    path('',views.home,name='forum-home'),
    path('insert/',views.insert,name = 'insert'),
    path('search/',views.search,name = 'search'),
    path('insert1/',views.insert1,name = 'insert1'),
]

home/views.py
from django.shortcuts import render,HttpResponse,redirect
import boto3
from boto3.dynamodb.conditions import Key, Attr
import random

# Create your views here.
def explore(request):
    uid=request.session['uid']
    dynamoDB=boto3.resource('dynamodb')
    dynamoTable=dynamoDB.Table('recipe')
    names=[]
    imglinks=[]
    rids=[]
    response = dynamoTable.scan()
    for i in response['Items']:
        names+=[i['name']]
        imglinks+=[i['Imglink']]
        rids+=[i['R_id']]
    name=[]
    imglink=[]
    rid=[]
    for x in range(0,4):
        rand=random.randint(1,100)
        name.append(names[rand])
        imglink.append(imglinks[rand])
        rid.append(rids[rand])

    return render(request, 'home/explore.html',{'data':zip(name,imglink,rid),'uid':uid})


def tryout(request):
    uid=request.session['uid']
    dynamoDB=boto3.resource('dynamodb')
    dynamoTable=dynamoDB.Table('recipe')
    names=[]
    imglinks=[]
    rids=[]
    response = dynamoTable.scan()
    for i in response['Items']:
        names+=[i['name']]
        imglinks+=[i['Imglink']]
        rids+=[i['R_id']]
    name=[]
    imglink=[]
    rid=[]
    for x in range(0,4):
        rand=random.randint(1,100)
        name.append(names[rand])
        imglink.append(imglinks[rand])
        rid.append(rids[rand])


    #### RECOMMENDOR SYSTEMS ####

    dynamoDB=boto3.resource('dynamodb')
    dynamoTable=dynamoDB.Table('Users')
    scan=dynamoTable.scan()
    count=len(scan['Items'])
    u=[]

    for i in range(1,count+1):
        u.append(i)

    dynamoDB=boto3.resource('dynamodb')
    dynamoTable=dynamoDB.Table('Recommend')
    scan=dynamoTable.scan()

    rvu=[]
    r=[]

    for i in scan['Items']:
        rvu.append(i['U_id'])
        r.append(i['R_id'])

    rvu_t = [list(i) for i in zip(*rvu)]

    ### FAMOUS ###
    top_recipes = [sum(i) for i in zip(*rvu_t)]

    n = len(top_recipes)
    temp_r = r

    for a in range(0, n):
        for j in range(0, n-a-1):
            if top_recipes[j] > top_recipes[j+1]:
                top_recipes[j], top_recipes[j+1] = top_recipes[j+1], top_recipes[j]
                temp_r[j], temp_r[j+1] = temp_r[j+1], temp_r[j]


    most_famous = []
    trending = []

    for i in range(0, 8):
        most_famous.append(temp_r[i])

    print(most_famous)

    for i in range(6, 10):
        trending.append(temp_r[i])

    print(trending)
    ################

    uid = request.session['uid']
    print(uid)
    sim = []
    i = u.index(uid)
    print(i)
    print(len(rvu_t))
    user_table = rvu_t[i]
    for user in rvu_t:
        sim.append(sum(user or user_table))

    n = len(u)
    temp_r = u

    for a in range(0, n):
        for j in range(0, n-a-1):
            if sim[j] > sim[j+1]:
                sim[j], sim[j+1] = sim[j+1], sim[j]
                temp_r[j], temp_r[j+1] = temp_r[j+1], temp_r[j]

    match_rps = []

    for k in range(0,5):
        match_rps.append(rvu_t[u.index(temp_r[k])])

    recom_rps = [sum(i) for i in zip(*match_rps)]

    n = len(top_recipes)
    temp_r = r

    for a in range(0, n):
        for j in range(0, n-a-1):
            if recom_rps[j] > recom_rps[j+1]:
                recom_rps[j], recom_rps[j+1] = recom_rps[j+1], recom_rps[j]
                temp_r[j], temp_r[j+1] = temp_r[j+1], temp_r[j]


    recommended_recipes = []

    for r in range(0,8):
        recommended_recipes.append(temp_r[r])

    print(recommended_recipes)

    dynamoDB=boto3.resource('dynamodb')
    dynamoTable=dynamoDB.Table('recipe')

    fst_spl = [178, 155, 169, 152]
    a=[]#8
    b=[]#8
    c=[]#4
    d=[]#4

    for i in recommended_recipes:
        response = dynamoTable.scan(
            FilterExpression=Attr('R_id').eq(int(i))
        )
        tp = []
        img =response['Items'][0]['Imglink']
        name =response['Items'][0]['name']
        rr = response['Items'][0]['R_id']
        tp.append(img)
        tp.append(name)
        tp.append(rr)
        a.append(tp)

    for i in most_famous:
        response = dynamoTable.scan(
            FilterExpression=Attr('R_id').eq(int(i))
        )
        tp = []
        img =response['Items'][0]['Imglink']
        name =response['Items'][0]['name']
        rr = response['Items'][0]['R_id']
        tp.append(img)
        tp.append(name)
        tp.append(rr)
        b.append(tp)

    for i in trending:
        response = dynamoTable.scan(
            FilterExpression=Attr('R_id').eq(int(i))
        )
        tp = []
        img =response['Items'][0]['Imglink']
        name =response['Items'][0]['name']
        rr = response['Items'][0]['R_id']
        tp.append(img)
        tp.append(name)
        tp.append(rr)
        c.append(tp)

    for i in fst_spl:
        response = dynamoTable.scan(
            FilterExpression=Attr('R_id').eq(int(i))
        )
        tp = []
        img =response['Items'][0]['Imglink']
        name =response['Items'][0]['name']
        rr = response['Items'][0]['R_id']
        tp.append(img)
        tp.append(name)
        tp.append(rr)
        d.append(tp)

    a1=[]
    dynamoDB=boto3.resource('dynamodb')
    dynamoTable=dynamoDB.Table('recipe')
    scan=dynamoTable.scan()
    for i in scan["Items"]:
        a1.append(i['name'])

    d1 = []
    for x in range(len(a1)):
        b1 = {}
        b1['id'] = x
        b1['value'] = a1[x]
        d1.append(b1)

    ### ACROSS FORUMS ###
    data = {'data':zip(name,imglink,rid),
            'trending':c,
            'recommended_recipes':a,
            'most_famous':b,
            'festival_splecial':d,
            'names':d1
            }

    return render(request, 'home/tryout.html', data)


def recipe(request, id):
    print(id)
    print(type(id))
    dynamoDB=boto3.resource('dynamodb')
    dynamoTable=dynamoDB.Table('recipe')
    response = dynamoTable.scan(
        FilterExpression=Attr('R_id').eq(int(id))
    )
    #data extraction
    servings    =response['Items'][0]['servings']
    ingredients =response['Items'][0]['ingreditents']
    chefname    =response['Items'][0]['Chefname']
    img         =response['Items'][0]['Imglink']
    maketime    =response['Items'][0]['Maketime']
    region      =response['Items'][0]['Region']
    steps       =response['Items'][0]['steps']
    name        =response['Items'][0]['name']
    description = response['Items'][0]['Description']

    print(description)
    x = [x.strip() for x in eval(steps)]
    del x[-1]

    n = len(x)

    x1 = [x1.strip() for x1 in eval(ingredients)]
    del x1[-1]

    n1 = len(x1)


    data = {'servings':servings,
            'ingredients':zip([x1+1 for x1 in list(range(n1))], x1),
            'chefname':chefname,
            'img':img,
            'maketime':maketime,
            'region':region,
            'steps':zip([x+1 for x in list(range(n))], x),
            'name':name,
            'n':n,
            'description':description[1:-1],
            'l':[x+1 for x in list(range(n))]}

    return render( request, 'home/recipe.html', data)

def base(request):
    return render(request, 'home/base.html')

def register(request):
    return render(request, 'register/login.html')

def findchefs(request):

    dynamoDB = boto3.resource('dynamodb')
    dynamoTable = dynamoDB.Table('Users')


    fe = Attr('email').contains('yashukikkuri@gmail.com')

    response = dynamoTable.scan(
         FilterExpression = fe,
         )

    following = response['Items'][0]['following']

    scan = dynamoTable.scan()
    top5 = []
    followers5=[]
    count = 0

    for i in scan['Items']:
        if(i['U_id'] in following):
            continue
        else:
            count+=1
            if(count>5):

                if(i['followers']>min(followers5)):
                    index=followers5.index(min(followers5))

                    a = []
                    response2 = dynamoTable.scan(
                        FilterExpression = Attr('U_id').eq(int(i['U_id']))
                    )
                    fname = response2['Items'][0]['fname']
                    uname = response2['Items'][0]['uname']
                    lname = response2['Items'][0]['lname']
                    followers = response2['Items'][0]['followers']

                    a.append(i['U_id'])
                    a.append(fname)
                    a.append(lname)
                    a.append(uname)
                    a.append(followers)

                    top5[index] = a

                    print(followers5)
                    print("\n\n")
                    print(top5)
                    print("\n\n")

            else:
                a = []
                response2 = dynamoTable.scan(
                    FilterExpression = Attr('U_id').eq(int(i['U_id']))
                )
                fname = response2['Items'][0]['fname']
                uname = response2['Items'][0]['uname']
                lname = response2['Items'][0]['lname']
                followers = response2['Items'][0]['followers']

                a.append(i['U_id'])
                a.append(fname)
                a.append(lname)
                a.append(uname)
                a.append(followers)

                top5.append(a)
                followers5.append(i['followers'])


    user_details = {'data': top5}

    return render(request, 'home/findchefs.html', user_details)


def registered(request):
    first = request.POST['First']
    last = request.POST['Last']
    email = request.POST['email']
    password = request.POST['password']
    uname=request.POST['username']
    dynamoDB = boto3.resource('dynamodb')
    dynamoTable = dynamoDB.Table('Users')
    fe = Attr('email').eq(email)
    response = dynamoTable.scan(FilterExpression = fe)

    if (response['Items']==[]):
        response=dynamoTable.scan()
        if (response['Items']==[]):
            sno = 1
        else:
            sno = len(response['Items'])+1
        dynamoTable.put_item(
        Item={
        'U_id':sno,
        'fname':first,
        'lname':last,
        'uname':uname,

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %} {% endblock %}</title>
  {% load static from staticfiles %}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/css/mdb.min.css" rel="stylesheet">



  <link rel="stylesheet" type="text/css" href="{% static 'home/explore.css' %}"/>

  <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/metropolis" type="text/css"/>
  {% block extrahead %}

  {% endblock %}

</head>

<body>


<!--Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #37703d">
  <a class="navbar-brand" href="#">FoodE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:home' %}">Home

        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:contact' %}">Contact us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:register' %}">Login/Register</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="#">My Account</a>
          <a class="dropdown-item" href="#">Liked recipes</a>
          <a class="dropdown-item" href="#">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!--/.Navbar -->

{% block body %}

{% endblock %}

<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5">

    <div style="background-color: #e2be47; position: relative;">
      <div class="container">

        <!-- Grid row-->
        <div class="row py-4 d-flex align-items-center">

          <!-- Grid column -->
          <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
            <h6 class="mb-0">Get connected with us on social networks!</h6>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-6 col-lg-7 text-center text-md-right">

            <!-- Facebook -->
            <a class="fb-ic">
              <i class="fab fa-facebook-f white-text mr-4"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic">
              <i class="fab fa-twitter white-text mr-4"> </i>
            </a>
            <!-- Google +-->
            <a class="gplus-ic">
              <i class="fab fa-google-plus-g white-text mr-4"> </i>
            </a>
            <!--Linkedin -->
            <a class="li-ic">
              <i class="fab fa-linkedin-in white-text mr-4"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fab fa-instagram white-text"> </i>
            </a>

          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row-->

      </div>
    </div>

    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">

      <!-- Grid row -->
      <div class="row mt-3 dark-grey-text">

        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

          <!-- Content -->
          <h6 class="text-uppercase font-weight-bold">FoodE</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>This website provides you a wide range of food recipes.We offer recipes based on different cuisines,ingredients,regions and many more</p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Cuisines</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a class="dark-grey-text" href="#!">Indian</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Mexcian</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Italian</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Chinese</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Useful links</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a class="dark-grey-text" href="#!">Your Account</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Add a Recipe</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Contact Us</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Help</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Contact</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <i class="fas fa-home mr-3"></i> IIIT Sri City, AP 517646, IND</p>
          <p>
            <i class="fas fa-envelope mr-3"></i> foodE@gmail.com</p>
          <p>
            <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
          <p>
            <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center text-black-50 py-3">© 2019 Copyright:
      <a class="dark-grey-text" href="index.html"> FoodE</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->


  <!-- SCRIPTS -->



<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/js/mdb.min.js"></script>

{% block script %}

{% endblock %}

</body>

</html>

home/templates/home/base1.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %} {% endblock %}</title>
  {% load static from staticfiles %}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/css/mdb.min.css" rel="stylesheet">



  <link rel="stylesheet" type="text/css" href="{% static 'home/explore.css' %}"/>

  <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/metropolis" type="text/css"/>
  {% block extrahead %}

  {% endblock %}

</head>

<body>


<!--Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #37703d">
  <a class="navbar-brand" href="#">FoodE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:tryout' %}">Explore</a>
        <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'uploadform:forum-home' %}">Upload Form</a>
      </li>
    

      <li class="nav-item">
        <a class="nav-link" href="{% url 'forum:forum' %}">Forum</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'uploadform:search' %}">Search</a>
      </li>


      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:cont' %}">Contact us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:home' %}">Logout</a>
      </li>
          </ul>
  </div>
</nav>
<!--/.Navbar -->

{% block body %}

{% endblock %}

<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5">

    <div style="background-color: #e2be47; position: relative;">
      <div class="container">

        <!-- Grid row-->
        <div class="row py-4 d-flex align-items-center">

          <!-- Grid column -->
          <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
            <h6 class="mb-0">Get connected with us on social networks!</h6>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-6 col-lg-7 text-center text-md-right">

            <!-- Facebook -->
            <a class="fb-ic">
              <i class="fab fa-facebook-f white-text mr-4"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic">
              <i class="fab fa-twitter white-text mr-4"> </i>
            </a>
            <!-- Google +-->
            <a class="gplus-ic">
              <i class="fab fa-google-plus-g white-text mr-4"> </i>
            </a>
            <!--Linkedin -->
            <a class="li-ic">
              <i class="fab fa-linkedin-in white-text mr-4"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fab fa-instagram white-text"> </i>
            </a>

          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row-->

      </div>
    </div>

    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">

      <!-- Grid row -->
      <div class="row mt-3 dark-grey-text">

        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

          <!-- Content -->
          <h6 class="text-uppercase font-weight-bold">FoodE</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>This website provides you a wide range of food recipes.We offer recipes based on different cuisines,ingredients,regions and many more</p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Cuisines</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a class="dark-grey-text" href="#!">Indian</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Mexcian</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Italian</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Chinese</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Useful links</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a class="dark-grey-text" href="#!">Your Account</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Add a Recipe</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Contact Us</a>
          </p>
          <p>
            <a class="dark-grey-text" href="#!">Help</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

          <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Contact</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <i class="fas fa-home mr-3"></i> IIIT Sri City, AP 517646, IND</p>
          <p>
            <i class="fas fa-envelope mr-3"></i> foodE@gmail.com</p>
          <p>
            <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
          <p>
            <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center text-black-50 py-3">© 2019 Copyright:
      <a class="dark-grey-text" href="index.html"> FoodE</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->


  <!-- SCRIPTS -->



<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/js/mdb.min.js"></script>

{% block script %}

{% endblock %}

</body>

</html>

home/templates/home/findchefs.html
<h2>Top Chefs</h2><br>

{% for i in data %}

<b>{{i}}</b><br>

{% endfor %}